quadrantsec/sagan-rules

README.md

Hey champ, can you get this out asap.

Made a change to the README.md

---

dynamic.rules

Removing MCAS from Zscaler to prevent FP's

Updated Dynamic Zscaler rule

---

linux-kernel.rules

Added new rules for polkit pkexec 0 day

Added new rules for polkit pkexec 0 day

---

systemd.rules

Update to SystemD rules per J Suain

Updated Systemd rules per JSuain

---

.last_used_sid
windows-powershell.rules

added 0 day rule and updated last SID

added rule for msdt 0-day cve 2022 30190

---

windows-misc.rules

2 new windows-misc rules for kerberoasting

fixing bad rules

---

.last_used_sid
normalization.rulebase
windows-powershell.rules

Sir, please approve these changes. I added to new powershell rules per Desorbo and the result of a customer incident as well as an new normalization rule to assist with a new custom rule for a customer. Lastly, I updated the last used sid.

Made changes to windows-powershell.rules, normalization.rulebase, & .last_used_sid

---

.last_used_sid
fortinet.rules
gcp-cloud-audit.rules

Created a rule for Fortinet VPN login failure (brute force 10 times/5 minutes)
Created a rule for Fortinet VPN login after brute force.
Modified the GCP Login Failure to reflect brute force activity (5 times within 1 minute)
Updated last_sid
Minor corrections
Disabled several rules that are not necessarily security related/actionable/useful

Rules modified for Fortinet.rules and GCP-cloud-audit.rules

---

.last_used_sid
duo.rules

Added a rule for DUO user put in to Bypass status

DUO Bypass Status Alert

---

classification.config

Classifications added and duplicates removed from https://rules.emergingthreats.net/open/suricata-5.0/rules/
Please review and consider this change.

Add ET Open Suricata Classifications

---

normalization.rulebase

Just some variable names that were bothering me.

Fix normalization var names

---

rules.yaml

Adds the rules template that contains all the rules file as well as some relevant comments.
@bryant-smith did the heavy lifting here. I just cleaned up some stray spaces.

add rules template

---

windows-auth.rules

Removed computer accounts on previous push.  Adding those back in.

Windows Auth

---

.last_used_sid
fortinet-json.rules
normalization.rulebase

**Fortinet**
Added ruleset for Fortinet JSON logs.  Same as the normal ruleset but converted to match JSON.
**Normalization**
Added normalization for event id 5145

Ruleset Update 01 Apr 2024

---

fortinet.rules

**fortinet.rules**
5006093: Reverted IP parsing for rule 5006093

Reverted IP parsing for rule 5006093

---

dynamic.rules

**Bomgar**
Corrected bomgar dynamic rule to load the correct rule file

Ruleset Update 10 July 2024

---

.last_used_sid
carbonblack-cloud.rules
carbonblack-endpoint-standard.rules

**CarbonBlack Cloud**
The carbon black logs format changed and the rules needed to be updated.
**CB Endpoint Standard**
Added reference link

Ruleset Update 16 Sept 2024

---

windows-auth.rules

**Windows Auth**
Updated rule to be more specific about when a user is added to the Domain Admins group.

Ruleset Update 19 Sept 2024

---

.last_used_sid
carbonblack-app-control.rules

updated rules because of a log change

Carbonblack

---

.last_used_sid
sonicwall.rules

**sonicwall.rules**
Created several new Sonicwall rules. There are 2 versions of each rule: One for generic syslog and one for events sent as JSON

New Rules - Sonicwall

---

classification.config

updated classifications

---

.last_used_sid
mcas.rules
msapi-securitycompliancecenter.rules
sentinelone.rules

**MCAS and MSAPI**
Rules added for cloud app security
**SentinelOne**
Rule Enabled

Ruleset Update 09 Jan 2025

---

.last_used_sid
cisco-meraki.rules

Rules added for spoofing and rogue ap

Cisco Meraki Air Marshal

---

.last_used_sid
cisco-meraki.rules
ubiquiti.rules

Cisco Meraki
Added config change rules
Ubiquiti
New ruleset added

Ruleset Update 09 June 2025
